Core/Instances: Fix build in older VS versions
Relax const uses in BossBoundaryEntry so the compiler can generate proper
copy assignment operator (error C2582: 'operator =' function is unavailable in 'BossBoundaryEntry')

Also renamed its members to match our coding standards
(public members should be UpperCamelCase)

(cherry picked from commit 954323d9cb13d4ab3d478bcb51eeb157009d8853)